### ISSUE TITLE
[Question]What's the purpose of adding a checkbox onto the box title?

### ISSUE THREAD

**Issue by happyshows** [harveyl888/shinyExtra#2]
Please elaborate, it's difficult for me to think about a use case around this feature.

**Comment by harveyl888** [comment]
Hi and thanks for trying out the panels.
The reason for the checkbox was that I'd put together an app where I had a number of panels, each of which was a separate section in a processing workflow and each panel contained a number of options.  

The checkbox provided an opportunity to select or deselect that section of a workflow.

This particular use-case is for processing data coming from an analytical chemistry experiment.  We had a panel with options for data reduction, another for statistics and another for data output.  By deselecting the panel for data reduction, the workflow would just run statistics and data output.
I apologize that It sounds a little confusing, and maybe a full example would help.
