### ISSUE TITLE
Update functions?

### ISSUE THREAD

**Issue by happyshows** [harveyl888/shinyExtra#5]
Hi,

I'm wondering if updateXXXX is on your development plan?

**Comment by harveyl888** [comment]
Which is updateXXXX?  I'd like to include the close button on the panels at some point.  This is a particularly busy month so it may have to wait till October.

**Comment by happyshows** [comment]
Hi,

I was referring to some function similar to updateTextInput or updateSelectInput. So that other reactive function can manipulate the value of SX components.

For example, I was trying to use SXSortable as display only component and use a selectize input to control the elements in SXSortable.

This is a nice to have option for me. Definitely close button (and listener behind it) has higher priority.
