### ISSUE TITLE
Bug in SXSortable coloring

### ISSUE THREAD

**Issue by happyshows** [harveyl888/shinyExtra#6]
The 2nd col does not display color properly after option dragged from 1st col to 2nd.

```
tagList(
      SXSortable('sort1', labels = list(list("label 1", "label 2", "label 3"), list("label 4", "label 5")), 
                 styleclass = list("success", "primary"), headers=list("title 1", "title 2"), height = 100),
    SXSortable('sxst_sb',list(list("label 1", "label 2", "label 3"),  list("test")), 
               styleclass = list("info", "success"),colorByGroup = T,
               headers=list("Not Included", "Included"))
    )
```

![image](https://cloud.githubusercontent.com/assets/3208181/18411836/efe36d4c-7745-11e6-8f18-71f8f9cf36d2.png)

**Comment by harveyl888** [comment]
Thanks for bringing this up.  I can reproduce and will look into a fix as soon as possible.  In the meantime a workaround is to remove the underscore from the id, eg sxstSb instead of sxst_sb.
