### ISSUE TITLE
for SXSortable, val_1/2 won't initialize in shiny unless triggered by user

### ISSUE THREAD

**Issue by happyshows** [harveyl888/shinyExtra#7]
Hi,

I found out this issue because I was expecting to read the default value in shiny, but it turns out to be NULL, unless user dragged the item to another frame.

**Comment by harveyl888** [comment]
Thanks for bringing this up.  Could you attach some reproducible code and I'll see if I can work on it this weekend.

**Comment by harveyl888** [comment]
Is the sortable function built within a renderUI call?  If so this is a known issue and can be solved using the workaround suggested in issue #4 and [example02](https://github.com/harveyl888/shinyExtra/tree/master/inst/examples/example02).  I'm looking into a more elegant solution.

**Comment by happyshows** [comment]
This workaround does the job.
